### PR TITLE
Removing Naked URL Redirect & JS Injection in 2.9.4 Docs

### PR DESCRIPTION
**Pull request by geobmx540**
The 2.9.4 docs are ancient docs build using Sandcastle. There is a security hole that allowos JS injection as well as redirects to any location.

Rather than try to parse and close the hole, we are removing the functionality to load different doc pages via querystring.

### CODE REVIEW

**Review by paulirwin — APPROVED** [review]

**Review by NightOwl888 — CHANGES_REQUESTED** [review]
As per the [docs](https://lucenenet.apache.org/contributing/documentation.html#deploy-the-website), the PR should target the asf-site branch, not master. Unfortunately, GitHub doesn't provide a way to change the target branch, so we will either need to close this PR and create a new PR or this has to be merged via command line to the asf-site branch.

I am a bit confused as to why we have a master branch in this repo, though. @Shazwazza - is there a reason we cannot set the default branch to asf-site and remove the master branch? I am guilty of not merging changes from asf-site into master, so it is probably out of date.

**Comment by geobmx540** [comment]
@NightOwl888 I was able to edit the PR target branch to merge into (done here to asf-site). However, I made the code change off of master. Should I also have branched off of asf-site for the code change and then point that target to asf-site in the apache repo? 

Happy to do whatever you feel is best.

**Comment by NightOwl888** [comment]
> @NightOwl888 I was able to edit the PR target branch to merge into (done here to asf-site). However, I made the code change off of master. Should I also have branched off of asf-site for the code change and then point that target to asf-site in the apache repo?

Yeah, we see some extra commits, so this is out of date. This is pretty easy to fix on the command line, though. Assuming your remote to this repo is named `upstream` and your fork is named `origin`:

## Ensure asf-site is up to date

```console
git fetch upstream asf-site
git checkout asf-site
git reset --hard upstream/asf-site
```


## Rebase security/docs_2.9.4_naked_redirect on top of asf-site

```console
git checkout security/docs_2.9.4_naked_redirect
git rebase asf-site
git push origin asf-site --force-with-lease
```
Since this file hasn't changed in years, this should not create any conflicts.

**Comment by Shazwazza** [comment]
@NightOwl888 

> I am a bit confused as to why we have a master branch in this repo, though. @Shazwazza - is there a reason we cannot set the default branch to asf-site and remove the master branch? I am guilty of not merging changes from asf-site into master, so it is probably out of date.

we don't have access to set the default branch so would need to go through apache for that if we wanted to change it IIRC.

**Comment by Shazwazza** [comment]
This is live now so now more XSS. 

image

**Pull request merged**
