### PR TITLE
New website build 667055b772d23227b03dfba12ec0e1f77ce6db5a

### PR DESCRIPTION
**Pull request by Shazwazza**
New website build on rev/tag 667055b772d23227b03dfba12ec0e1f77ce6db5a
For release version (no tag)

### CODE REVIEW

**Comment by NightOwl888** [comment]
Is it too late to add another page?

During the last release I added the release notes to the site so they could go out in the vote email and people without permissions could see them. I would like to add the release notes again now (I already have them marked up).

**Comment by Shazwazza** [comment]
This was an automated build from my repo :) I just changed the target to the live one instead of my test one, see https://github.com/Shazwazza/lucenenet/actions/runs/686491799

So it's super easy to just make another build, no problemo! Much easier if this was automated in our own repo but at least I can automate it from my external one.

**Comment by Shazwazza** [comment]
I'll merge these changes and then can just push a new one, just let me know when you've pushed your changes to master

**Comment by NightOwl888** [comment]
> I'll merge these changes and then can just push a new one, just let me know when you've pushed your changes to master

Gotcha.

**Comment by NightOwl888** [comment]
Alright, I have pushed to master. So I guess this means you own deployments now? Or will the automated process open a PR that I can merge?

**Comment by Shazwazza** [comment]
I'll just kick off another run and it will create another PR here

**Comment by Shazwazza** [comment]
Once Infra gets that PAT task done then it will be all automated directly from making site changes.

**Pull request merged**
