### PR TITLE
New website build 042ec4f3baf9a78104e55117f44b5b0248a849c0

### PR DESCRIPTION
**Pull request by Shazwazza**
New website build on rev/tag 042ec4f3baf9a78104e55117f44b5b0248a849c0
For release version (no tag)

### CODE REVIEW

**Comment by Shazwazza** [comment]
@NightOwl888 here's the generated PR, feel free to merge 🚀

**Comment by NightOwl888** [comment]
Cool. You are my hero.

**Comment by Shazwazza** [comment]
Lol 😂 makes it a little easier to do!

**Comment by NightOwl888** [comment]
@Shazwazza 

I just pushed some changes to the release notes (benchmarks and known issues). Could we push the site again?

**Comment by Shazwazza** [comment]
@NightOwl888 yep, a new PR is here https://github.com/apache/lucenenet-site/pull/13 i'll merge 🚀

**Comment by Shazwazza** [comment]
@NightOwl888 As a work around for now, I've added you to as a user to my fork: https://github.com/Shazwazza/lucenenet if you want to generate a build, just add this repo as a remote repository and push changes from the `master` branch to this repository's [`website-build-automation`](https://github.com/Shazwazza/lucenenet/tree/website-build-automation) branch and it will build the site and create a PR.

**Pull request merged**
