### PR TITLE
New build with the correct links for the Improve this Doc button

### PR DESCRIPTION
**Pull request by Shazwazza**
This fixes the improve this doc button, this is the site output based on this change https://github.com/apache/lucenenet/pull/225 ... which also needs to be merged into the main repo

### CODE REVIEW

**Comment by Shazwazza** [comment]
bump! just wanted to bump this one to see if we can get this merged? maybe @laimis  is around?

**Comment by sisve** [comment]
Do I need to do anything more to fix this, or is merging the PR enough?

**Comment by Shazwazza** [comment]
Just merging is good, thanks!

**Comment by Shazwazza** [comment]
Hi @sisve , I know this is super old but it turns out more is needed for this. I didn't realize that the site actually runs on the branch: `asf-site`, any chance you could merge master -> asf-site?

**Pull request merged**
